# change the followings to match your Github username and repo name
baseurl: "/wip-masquerading-gals" # the name of your github repo
url: "https://BCDigSchol.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Love Cults, Masquerading Gals, and Subway Sammies"
description: Jekyll site for the Love Cults, Masquerading Gals, and Subway Sammies Project @ Boston College

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# nav bar settings and links
nav-menu:
  - title: Home
    link: index
  - title: Terminology
    link: terminology
  - title: General Findings
    link: general-findings
  - title: Decades
    submenu:
    - title: 1940s
      link: 1940s
    - title: 1950s
      link: 1950s
    - title: 1960s
      link: 1960s
  - title: Analyses
    submenu:
    - title: LGBTQ+ Accounts
      link: lgbtq-accounts
    - title: Queer Homes
      link: queer-homes
  - title: Bibliography
    link: bibliography
  - title: Events
    link: events
  - title: About
    link: about

# sets whether a search bar appears on the site header
# NOTE, you will have to increase the site of teh $site-header-height in _sass/theme-settings.scss to to see the search bar
search-bar: false

hide-footer: false # set to true to hide the footer
footer-message: "Love Cults, Masquerading Gals, and Subway Sammies | CC BY-NC License"
footer-submessage:  By Sam Hurwitz, with the Digital Scholarship Group, Boston College
footer-submessage-link: https://ds.bc.edu

# google-analytics: // if you want to use Google analytics, include your ID here

# sets number of items display per page, if using a blog
paginate: 5

include:
  - _pages

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
    - jekyll-feed
    - jekyll-paginate
    - jekyll-postcss-v2
